Resolves: 207457 Summary: Added 64-bit atomic functions for platforms lacking built-ins.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -23358,7 +23358,7 @@ initdir=/rc.d
 # those with our 64 bit compiled product.
 perlexec='/usr/bin/env perl'
 case $host in
-  *-*-linux*)
+  i*86-*-linux*)
 
 cat >>confdefs.h <<\_ACEOF
 #define XP_UNIX 1
@@ -23391,6 +23391,11 @@ _ACEOF
 
 
 cat >>confdefs.h <<\_ACEOF
+#define CPU_x86
+_ACEOF
+
+
+cat >>confdefs.h <<\_ACEOF
 #define _GNU_SOURCE 1
 _ACEOF
 
@@ -23398,6 +23403,200 @@ _ACEOF
 cat >>confdefs.h <<\_ACEOF
 #define ATOMIC_64BIT_OPERATIONS 1
 _ACEOF
+
+    echo "$as_me:$LINENO: checking whether __sync_add_and_fetch is declared" >&5
+echo $ECHO_N "checking whether __sync_add_and_fetch is declared... $ECHO_C" >&6
+if test "${ac_cv_have_decl___sync_add_and_fetch+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+$ac_includes_default
+int
+main ()
+{
+#ifndef __sync_add_and_fetch
+  char *p = (char *) __sync_add_and_fetch;
+#endif
+
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_c_werror_flag"
+			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_have_decl___sync_add_and_fetch=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+ac_cv_have_decl___sync_add_and_fetch=no
+fi
+rm -f conftest.err conftest.$ac_objext conftest.$ac_ext
+fi
+echo "$as_me:$LINENO: result: $ac_cv_have_decl___sync_add_and_fetch" >&5
+echo "${ECHO_T}$ac_cv_have_decl___sync_add_and_fetch" >&6
+if test $ac_cv_have_decl___sync_add_and_fetch = yes; then
+
+cat >>confdefs.h <<_ACEOF
+#define HAVE_DECL___SYNC_ADD_AND_FETCH 1
+_ACEOF
+
+
+else
+  cat >>confdefs.h <<_ACEOF
+#define HAVE_DECL___SYNC_ADD_AND_FETCH 0
+_ACEOF
+
+
+fi
+
+
+    platform="linux"
+    # relative to sysconfdir
+    initdir=/rc.d/init.d
+    ;;
+  x86_64-*-linux*)
+
+cat >>confdefs.h <<\_ACEOF
+#define XP_UNIX 1
+_ACEOF
+
+
+cat >>confdefs.h <<\_ACEOF
+#define Linux 1
+_ACEOF
+
+
+cat >>confdefs.h <<\_ACEOF
+#define LINUX 1
+_ACEOF
+
+
+cat >>confdefs.h <<\_ACEOF
+#define LINUX2_0 1
+_ACEOF
+
+
+cat >>confdefs.h <<\_ACEOF
+#define LINUX2_2 1
+_ACEOF
+
+
+cat >>confdefs.h <<\_ACEOF
+#define LINUX2_4 1
+_ACEOF
+
+
+cat >>confdefs.h <<\_ACEOF
+#define CPU_x86_64
+_ACEOF
+
+
+cat >>confdefs.h <<\_ACEOF
+#define _GNU_SOURCE 1
+_ACEOF
+
+
+cat >>confdefs.h <<\_ACEOF
+#define ATOMIC_64BIT_OPERATIONS 1
+_ACEOF
+
+    echo "$as_me:$LINENO: checking whether __sync_add_and_fetch is declared" >&5
+echo $ECHO_N "checking whether __sync_add_and_fetch is declared... $ECHO_C" >&6
+if test "${ac_cv_have_decl___sync_add_and_fetch+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+$ac_includes_default
+int
+main ()
+{
+#ifndef __sync_add_and_fetch
+  char *p = (char *) __sync_add_and_fetch;
+#endif
+
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_c_werror_flag"
+			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_have_decl___sync_add_and_fetch=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+ac_cv_have_decl___sync_add_and_fetch=no
+fi
+rm -f conftest.err conftest.$ac_objext conftest.$ac_ext
+fi
+echo "$as_me:$LINENO: result: $ac_cv_have_decl___sync_add_and_fetch" >&5
+echo "${ECHO_T}$ac_cv_have_decl___sync_add_and_fetch" >&6
+if test $ac_cv_have_decl___sync_add_and_fetch = yes; then
+
+cat >>confdefs.h <<_ACEOF
+#define HAVE_DECL___SYNC_ADD_AND_FETCH 1
+_ACEOF
+
+
+else
+  cat >>confdefs.h <<_ACEOF
+#define HAVE_DECL___SYNC_ADD_AND_FETCH 0
+_ACEOF
+
+
+fi
+
 
     platform="linux"
     # relative to sysconfdir
