Ticket 457 - dirsrv init script returns 0 even when few or all instances fail to start
Bug Description:  We don't return an error code when one or more instances fails to start.

Fix Description:  Return error 1 when an instance fails to start.

https://fedorahosted.org/389/ticket/457

Reviewed by: richm(Thanks!)

diff --git a/wrappers/initscript.in b/wrappers/initscript.in
--- a/wrappers/initscript.in
+++ b/wrappers/initscript.in
@@ -264,7 +264,8 @@ start() {
         [ -x /sbin/restorecon ] && /sbin/restorecon $lockfile
     fi
     if [ $errors -ge 1 ]; then
-        echo "  *** Warning: $errors instance(s) failed to start"
+        echo "  *** Error: $errors instance(s) failed to start"
+        exit 1
     fi
 }
 
