Ticket 47662 - Better input argument validation and error messages for cli tools
Description:  Improved usage errors for CLI tools, and also made the usage errors
              consistent.

https://fedorahosted.org/389/ticket/47662

Reviewed by: nhosoi(Thanks!)

diff --git a/ldap/admin/src/scripts/db2bak.in b/ldap/admin/src/scripts/db2bak.in
--- a/ldap/admin/src/scripts/db2bak.in
+++ b/ldap/admin/src/scripts/db2bak.in
@@ -53,6 +53,13 @@ do
     esac
 done
 
+shift $(($OPTIND - 1))
+if [ $1 ]
+then
+    echo "ERROR - Unknown option: $1"
+    usage
+    exit 1
+fi
 
 initfile=$(get_init_file "@initconfigdir@" $servid)
 if [ $? -eq 1 ]
diff --git a/ldap/admin/src/scripts/db2ldif.in b/ldap/admin/src/scripts/db2ldif.in
--- a/ldap/admin/src/scripts/db2ldif.in
+++ b/ldap/admin/src/scripts/db2ldif.in
@@ -130,6 +130,14 @@ do
     esac
 done
 
+shift $(($OPTIND - 1))
+if [ $1 ]
+then
+    echo "ERROR - Unknown option: $1"
+    usage
+    exit 1
+fi
+
 if [ "$required_param" != "yes" ]
 then
     usage
diff --git a/ldap/admin/src/scripts/ldif2db.in b/ldap/admin/src/scripts/ldif2db.in
--- a/ldap/admin/src/scripts/ldif2db.in
+++ b/ldap/admin/src/scripts/ldif2db.in
@@ -81,6 +81,20 @@ do
     esac
 done
 
+if [ $# -lt 4 ]
+then
+    usage
+    exit 1
+fi
+
+shift $(($OPTIND - 1))
+if [ $1 ]
+then
+    echo "ERROR - Unknown option: $1"
+    usage
+    exit 1
+fi
+
 initfile=$(get_init_file "@initconfigdir@" $servid)
 if [ $? -eq 1 ]
 then
@@ -91,12 +105,6 @@ then
 fi
 
 . $initfile
-
-if [ $# -lt 4 ]
-then
-    usage
-    exit 1
-fi
 
 handleopts $@
 quiet=$?
diff --git a/ldap/admin/src/scripts/suffix2instance.in b/ldap/admin/src/scripts/suffix2instance.in
--- a/ldap/admin/src/scripts/suffix2instance.in
+++ b/ldap/admin/src/scripts/suffix2instance.in
@@ -38,6 +38,20 @@ then
     exit 1
 fi
 
+if [ $# -lt 2 ]
+then
+    echo Usage: suffix2instance [-Z serverID] {-s includesuffix}*
+    exit 1
+fi
+
+shift $(($OPTIND - 1))
+if [ $1 ]
+then
+    echo "ERROR - Unknown option: $1"
+    usage
+    exit 1
+fi
+
 initfile=$(get_init_file "@initconfigdir@" $servid)
 if [ $? -eq 1 ]
 then
@@ -49,10 +63,6 @@ fi
 
 . $initfile
 
-if [ $# -lt 2 ]
-then
-    echo Usage: suffix2instance [-Z serverID] {-s includesuffix}*
-    exit 1
-fi
+
 
 eval @sbindir@/ns-slapd suffix2instance -D $CONFIG_DIR $args 2>&1
diff --git a/ldap/admin/src/scripts/upgradednformat.in b/ldap/admin/src/scripts/upgradednformat.in
--- a/ldap/admin/src/scripts/upgradednformat.in
+++ b/ldap/admin/src/scripts/upgradednformat.in
@@ -49,6 +49,14 @@ do
     esac
 done
 
+shift $(($OPTIND - 1))
+if [ $1 ]
+then
+    echo "ERROR - Unknown option: $1"
+    usage
+    exit 1
+fi
+
 if [ -z "$be" ] || [ -z "$dir" ]; then
     usage
     exit 1
diff --git a/ldap/admin/src/scripts/vlvindex.in b/ldap/admin/src/scripts/vlvindex.in
--- a/ldap/admin/src/scripts/vlvindex.in
+++ b/ldap/admin/src/scripts/vlvindex.in
@@ -44,6 +44,20 @@ do
     esac
 done
 
+if [ $# -lt 4 ]
+then
+    usage
+    exit 1
+fi
+
+shift $(($OPTIND - 1))
+if [ $1 ]
+then
+    echo "ERROR - Unknown option: $1"
+    usage
+    exit 1
+fi
+
 initfile=$(get_init_file "@initconfigdir@" $servid)
 if [ $? -eq 1 ]
 then
@@ -54,11 +68,5 @@ then
 fi
 
 . $initfile
-
-if [ $# -lt 4 ]
-then
-    usage
-    exit 1
-fi
 
 eval @sbindir@/ns-slapd db2index -D $CONFIG_DIR $args
