Trac Ticket #451 - Allow db2ldif to be quiet
https://fedorahosted.org/389/ticket/451

Description: Export utility db2ldif and import utility ldif2db are
always verbose.  This patch is adding an option '-q' to suppress
the outputs.

This patch modifies db2bak and bak2db which already supports '-q',
as well.  The scripts used to interpret '-q'.  If it was not set,
a verbose debug option '-d 524288' was passed to ns-slapd.  Instead,
this patch directly passes '-q' to ns-slapd and let it handle it
in the C code.

diff --git a/ldap/admin/src/scripts/template-ldif2db.in b/ldap/admin/src/scripts/template-ldif2db.in
--- a/ldap/admin/src/scripts/template-ldif2db.in
+++ b/ldap/admin/src/scripts/template-ldif2db.in
@@ -19,15 +19,40 @@ export LD_LIBRARY_PATH
 SHLIB_PATH=$LD_LIBRARY_PATH
 export SHLIB_PATH
 
+usage()
+{
+    echo "Usage: ldif2db -n backend_instance | {-s includesuffix}* [{-x excludesuffix}*]"
+    echo "               {-i ldiffile}* [-O] [-q]"
+    echo "Note: either \"-n backend_instance\" or \"-s includesuffix\" and \"-i ldiffile\" are required."
+}
+
+handleopts()
+{
+    while [ "$1" != "" ]
+    do
+        if [ "$1" = "-q" ]; then
+            return 1
+        elif [ "$1" = "-h" ]; then
+            usage
+            exit 1
+        fi
+        shift
+    done
+    return 0
+}
+
 cd {{SERVERBIN-DIR}}
 if [ $# -lt 4 ]
 then
-	echo "Usage: ldif2db -n backend_instance | {-s includesuffix}* [{-x excludesuffix}*]"
-	echo "               {-i ldiffile}* [-O]"
-	echo "Note: either \"-n backend_instance\" or \"-s includesuffix\" and \"-i ldiffile\" are required."
-	exit 1
+    usage
+    exit 1
 fi
 
-echo importing data ...
+handleopts $@
+quiet=$?
+
+if [ $quiet -eq 0 ]; then
+    echo importing data ...
+fi
 ./ns-slapd ldif2db -D {{CONFIG-DIR}} "$@" 2>&1
 exit $?
